// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiyaxqofbfzwvfrfnaat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppeWF4cW9mYmZ6d3ZmcmZuYWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MjU2NzQsImV4cCI6MjA2OTEwMTY3NH0.-m_vWZmplluA2xwjQT-idV2c9spqZbt4dPeTGr57dEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});